apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rcb
  name: rcb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rcb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rcb
    spec:
      containers:
      - image: demoaksacr2.azurecr.io/rcb
        name: rcb
        ports:
        - containerPort: 80
        resources: {}
status: {}
